services:
  - type: web
    name: todo-api
    env: python
    buildCommand: pip install -r backend/requirements_render.txt
    startCommand: cd backend && gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: todo-app-db
          property: connectionString
      - key: FLASK_ENV
        value: production

databases:
  - name: todo-app-db
    plan: free
